Enable self-collisions in Gazebo
UHHRobotics22-23/marimbabot pull request #127
Opened 2023-06-01 13:24 UTC by iibrahimli

Enable self-collisions in Marimba UR5 URDF

Closes #121

2023-06-07 19:57 UTC, Juphex requested changes
As I understood the complete model is now enabled to have a collision. Doesn't it make more sence to enable it only for specific parts like the bars? at least for the start

2023-06-07 19:57 UTC, Juphex commented on marimbabot_description/urdf/marimba.urdf.xacro
> +    <xacro:unless value="${arg bars_fixed_joint}">
Please revert. Doesn't work with curly brackets. At least not for me 😅

2023-06-07 19:57 UTC, Juphex commented on marimbabot_description/urdf/marimba.urdf.xacro
> +    <xacro:if value="${arg bars_fixed_joint}">
same

2023-06-07 19:57 UTC, Juphex commented on marimbabot_description/urdf/marimba.urdf.xacro
> +    <xacro:unless value="${arg bars_fixed_joint}">
At least when I start it in rviz.

2023-06-08 10:35 UTC, iibrahimli commented
> As I understood right now: the complete model is now enabled to have a collision. Doesn't it make more sence to enable it only for specific parts like the bars? at least for the start

@Juphex In that case mallet/arm would go right through side boxes or body, which is not the desired behavior.

2023-06-08 10:59 UTC, Juphex approved these changes

2023-06-08 10:59 UTC, Juphex commented
works

2023-06-08 11:31 UTC, merged