Add vision evaluation script
UHHRobotics22-23/MarimbaBot pull request #284
Opened 2023-10-05 21:48 UTC by Flova

Add a script that evaluates a given model on a given dataset outside of the training

2023-10-10 13:21 UTC, Juphex requested changes
Doesnt work for me. Do we need any permissions?


```

model_artificial_char_2 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/model_artificial_char_2/resolve/main/config.json

The above exception was the direct cause of the following exception:

huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-65254f76-1a51cedd62298aa73f0b0e53;6689850a-0ffa-41c9-ba3c-7d6a47d65673)

```

2023-10-14 16:55 UTC, Flova commented
The model you are trying to evaluate is a offline one on my machine. We can switch the default to the remote address on huggingface.

2023-10-16 11:31 UTC, Flova commented
Ping @Juphex

2023-10-16 15:58 UTC, Juphex approved these changes

2023-10-16 15:59 UTC, merged