Create README.md
UHHRobotics22-23/marimbabot pull request #288
Opened 2023-10-11 16:55 UTC by yunlong-wang-cn

add readme to bringup

2023-10-12 11:47 UTC, berkgungor requested changes

2023-10-12 19:51 UTC, ateRstones commented
I think the pr #291 already implemented this

2023-10-14 16:23 UTC, Flova commented on marimbabot_bringup/README.md
> +1.  Launch the `marimbabot_ur5_bringup.launch` to bringup the serivce of the UR5 robot. **By launching this file, the robot's gripper could reinitialize itself, so what is holded by the gripper could
Maybe rename to driver instead of service

2023-10-14 16:24 UTC, Flova commented on marimbabot_bringup/README.md
> +1.  Launch the `marimbabot_ur5_bringup.launch` to bringup the serivce of the UR5 robot. **By launching this file, the robot's gripper could reinitialize itself, so what is holded by the gripper could
"what is holded by the gripper could fall down**" -> " anything held by the gripper is dropped!**"

2023-10-14 16:24 UTC, Flova approved these changes

2023-10-14 16:26 UTC, Flova commented
> I think the pr #291 already implemented this

Oh you are correct. But we could still add the warning, detailing, that things might be dropped during startup.

2023-10-14 16:27 UTC, Flova requested changes
See the other comment

2023-10-14 16:30 UTC, yunlong-wang-cn reviewed
update doc

2023-10-14 16:31 UTC, yunlong-wang-cn commented
resolve conflict and just add the warning from #291.

2023-10-14 16:47 UTC, Flova approved these changes

2023-10-14 16:47 UTC, Flova approved these changes

2023-10-14 16:48 UTC, merged