Audio output of detected notes
UHHRobotics22-23/marimbabot pull request #64
Opened 2023-04-17 19:04 UTC by Juphex

Closes https://github.com/UHHRobotics22-23/marimbabot/issues/39

2023-04-20 11:15 UTC, Juphex commented
I need to test it yet

2023-04-21 11:20 UTC, Flova requested changes

2023-04-21 11:20 UTC, Flova commented on marimbabot_audio/src/audio_from_lilypond.py
> +    # it is hardcoded for now, could be changed to a temporary file as well
I think we should definitely make it a temp file

2023-04-21 11:20 UTC, Flova commented on marimbabot_audio/src/audio_from_lilypond.py
> +    rospy.init_node('visualization_node')
The node name is prone to namespace issues. Maybe all audio to it.

2023-04-27 12:20 UTC, Juphex commented
the package midi2audio depends on fluidsynth https://github.com/ros/rosdistro/pull/37007

2023-05-02 18:04 UTC, Flova approved these changes

2023-05-03 12:49 UTC, Juphex commented
I accidentally pushed some dev files... @Flova

2023-05-07 21:45 UTC, Juphex commented
I resolved the merge conflicts with the main branch but I am not sure about all the imports that are within the main https://github.com/UHHRobotics22-23/marimbabot/pull/17#issuecomment-1537545534.

2023-05-07 22:00 UTC, merged